POST http://localhost:8080/api/v1/books
Content-Type: application/json

{
  "bookName" : "Simpsons Comics",
  "issueNumber" : 94,
  "publishDate" : "May 2004",
  "description" : "24/7th Heaven"
}

###

POST http://localhost:8080/api/v1/books
Content-Type: application/json

{
"bookName" : "Simpsons Comics",
"issueNumber" : 95,
"publishDate" : "June 2004",
"description" : "Coach Me If You Can"
}

###

POST http://localhost:8080/api/v1/books
Content-Type: application/json

{
  "bookName" : "Simpsons Comics",
  "issueNumber" : 96,
  "publishDate" : "July 2004",
  "description" : "A Tale of 2 Pen Pals"
}

###

POST http://localhost:8080/api/v1/books
Content-Type: application/json

{
  "bookName" : "Simpsons Comics",
  "issueNumber" : 97,
  "publishDate" : "August 2004",
  "description" : "Feud, Glorious Feud"
}

###

POST http://localhost:8080/api/v1/books
Content-Type: application/json

{
  "bookName" : "Simpsons Comics",
  "issueNumber" : 98,
  "publishDate" : "September 2004",
  "description" : "The Return of Xt'tapalatakettle"
}

###

POST http://localhost:8080/api/v1/books
Content-Type: application/json

{
  "bookName" : "Simpsons Comics",
  "issueNumber" : 99,
  "publishDate" : "October 2004",
  "description" : "Marge Simens Living"
}

### update

PUT http://localhost:8080/api/v1/books
Content-Type: application/json

{
  "bookName" : "Simpsons Comics",
  "issueNumber" : 99,
  "publishDate" : "October 2004",
  "description" : "Marge Simpson Living"
}

###

PUT http://localhost:8080/api/v1/books/up/id=SimpsonsComics94

###

#GET http://localhost:8080/api/v1/books/id=SimpsonsComics94

###

GET http://localhost:8080/api/v1/books?page=0&size=2

###

#GET http://localhost:8080/api/v1/books/?page=0&size=2

###

#{
#"displayedName" : "Matt Groening",
#    "UserType" : "writer"
#}